name: release

on:
  push:
    # tags:
    # - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build:
    name: build (${{ matrix.config.os }}, ${{ matrix.config.arch }})
    runs-on:
      ubuntu-latest
    strategy:
      matrix:
        config:
          - os: linux
            arch: amd64
            cross_compile: x86_64-ubuntu16.04-linux-gnu
          - os: linux
            arch: 386
            cross_compile: i686-ubuntu16.04-linux-gnu
          - os: linux
            arch: arm
            cross_compile: arm-linux-gnueabihf
          - os: linux
            arch: arm64
            cross_compile: aarch64-linux-gnu
          - os: darwin
            arch: amd64
            cross_compile: x86_64-apple-darwin13
            cross_compiler: o64-clang
          - os: windows
            arch: 386
            cross_compile: i686-w64-mingw32
            extension: .exe

    container:
      image: ghcr.io/arduino/crossbuild:0.2.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.AVRDUDE_CI_PAT }}
    
    steps:
    - name: Checkout avrdude repository
      uses: actions/checkout@v2

    - name: Build Avrdude
      run: |
        if [ "${{ matrix.config.os }}" = "darwin" ]; then
          cmake -DCMAKE_C_COMPILER=${{ matrix.config.cross_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cross_compiler }}++ -DCMAKE_EXE_LINKER_FLAGS="-static-libgcc -static-libstdc++" -DCMAKE_C_FLAGS="-I/opt/lib/$CROSS_COMPILE/include/libusb-1.0/ -I/opt/lib/$CROSS_COMPILE/include -pthread" -DCMAKE_PREFIX_PATH=/opt/lib/$CROSS_COMPILE/ -DHAVE_LIBFTDI="NO" -B build/
        else
          cmake -DCMAKE_C_COMPILER=${{ matrix.config.cross_compile }}-gcc -DCMAKE_CXX_COMPILER=${{ matrix.config.cross_compile }}-g++ -DCMAKE_EXE_LINKER_FLAGS="-static-libgcc -static-libstdc++" -DCMAKE_C_FLAGS="-I/opt/lib/$CROSS_COMPILE/include/libusb-1.0/ -I/opt/lib/$CROSS_COMPILE/include -pthread" -DCMAKE_PREFIX_PATH=/opt/lib/$CROSS_COMPILE/ -DHAVE_LIBFTDI="NO" -B build/
        fi
        cmake --build build/ -v

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: avrdude_${{matrix.config.os}}_${{matrix.config.arch}}
        path: |
          build/src/avrdude${{ matrix.config.extension }}
          build/src/avrdude.conf
